
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Entry E_usr;

	private global::Gtk.Label L_User;

	private global::Gtk.Label L_Passw;

	private global::Gtk.Entry entry4;

	private global::Gtk.Button btn_Salir;

	private global::Gtk.Button btn_ok;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.WidthRequest = 200;
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.E_usr = new global::Gtk.Entry();
		this.E_usr.WidthRequest = 245;
		this.E_usr.CanFocus = true;
		this.E_usr.Name = "E_usr";
		this.E_usr.IsEditable = true;
		this.E_usr.InvisibleChar = '●';
		this.fixed1.Add(this.E_usr);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.E_usr]));
		w1.X = 54;
		w1.Y = 70;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.L_User = new global::Gtk.Label();
		this.L_User.Name = "L_User";
		this.L_User.Xalign = 0F;
		this.L_User.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
		this.fixed1.Add(this.L_User);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.L_User]));
		w2.X = 54;
		w2.Y = 50;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.L_Passw = new global::Gtk.Label();
		this.L_Passw.Name = "L_Passw";
		this.L_Passw.LabelProp = global::Mono.Unix.Catalog.GetString("Contrasena:");
		this.fixed1.Add(this.L_Passw);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.L_Passw]));
		w3.X = 54;
		w3.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry4 = new global::Gtk.Entry();
		this.entry4.WidthRequest = 245;
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.Visibility = false;
		this.entry4.InvisibleChar = '●';
		this.fixed1.Add(this.entry4);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry4]));
		w4.X = 54;
		w4.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_Salir = new global::Gtk.Button();
		this.btn_Salir.WidthRequest = 100;
		this.btn_Salir.CanFocus = true;
		this.btn_Salir.Name = "btn_Salir";
		this.btn_Salir.UseUnderline = true;
		this.btn_Salir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.fixed1.Add(this.btn_Salir);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_Salir]));
		w5.X = 194;
		w5.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btn_ok = new global::Gtk.Button();
		this.btn_ok.WidthRequest = 100;
		this.btn_ok.CanFocus = true;
		this.btn_ok.Name = "btn_ok";
		this.btn_ok.UseUnderline = true;
		this.btn_ok.Label = global::Mono.Unix.Catalog.GetString("Aceptar");
		this.fixed1.Add(this.btn_ok);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_ok]));
		w6.X = 54;
		w6.Y = 190;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 355;
		this.DefaultHeight = 255;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
