
// This file has been generated by the GUI designer. Do not modify.
namespace SPC
{
	public partial class Supervisor
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SPC.Supervisor
			this.Name = "SPC.Supervisor";
			this.Title = global::Mono.Unix.Catalog.GetString("Supervisor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
