
// This file has been generated by the GUI designer. Do not modify.
namespace SPC
{
	public partial class Operador_Datos
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Table table3;

		private global::Gtk.Entry E1;

		private global::Gtk.Entry E10;

		private global::Gtk.Entry E2;

		private global::Gtk.Entry E3;

		private global::Gtk.Entry E4;

		private global::Gtk.Entry E5;

		private global::Gtk.Entry E6;

		private global::Gtk.Entry E7;

		private global::Gtk.Entry E8;

		private global::Gtk.Entry E9;

		private global::Gtk.Entry entry24;

		private global::Gtk.Entry entry26;

		private global::Gtk.Entry entry28;

		private global::Gtk.Entry entry30;

		private global::Gtk.Entry entry32;

		private global::Gtk.Entry entry34;

		private global::Gtk.Entry entry36;

		private global::Gtk.Entry entry38;

		private global::Gtk.Entry entry40;

		private global::Gtk.Entry entry42;

		private global::Gtk.Entry entry44;

		private global::Gtk.Entry entry46;

		private global::Gtk.Entry entry48;

		private global::Gtk.Entry entry50;

		private global::Gtk.Entry entry52;

		private global::Gtk.Entry entry54;

		private global::Gtk.Entry entry56;

		private global::Gtk.Entry entry58;

		private global::Gtk.Entry entry60;

		private global::Gtk.Entry entry62;

		private global::Gtk.Label L_Ins;

		private global::Gtk.Button btn_Cnl;

		private global::Gtk.Button btn_ok;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SPC.Operador_Datos
			this.Name = "SPC.Operador_Datos";
			this.Title = global::Mono.Unix.Catalog.GetString("Ingreso de datos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SPC.Operador_Datos.Gtk.Container+ContainerChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.table3 = new global::Gtk.Table(((uint)(10)), ((uint)(3)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.E1 = new global::Gtk.Entry();
			this.E1.CanFocus = true;
			this.E1.Name = "E1";
			this.E1.IsEditable = true;
			this.E1.InvisibleChar = '●';
			this.table3.Add(this.E1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.E1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E10 = new global::Gtk.Entry();
			this.E10.CanFocus = true;
			this.E10.Name = "E10";
			this.E10.IsEditable = true;
			this.E10.InvisibleChar = '●';
			this.table3.Add(this.E10);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.E10]));
			w3.TopAttach = ((uint)(9));
			w3.BottomAttach = ((uint)(10));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E2 = new global::Gtk.Entry();
			this.E2.CanFocus = true;
			this.E2.Name = "E2";
			this.E2.IsEditable = true;
			this.E2.InvisibleChar = '●';
			this.table3.Add(this.E2);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.E2]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(0));
			w4.YOptions = ((global::Gtk.AttachOptions)(1));
			// Container child table3.Gtk.Table+TableChild
			this.E3 = new global::Gtk.Entry();
			this.E3.CanFocus = true;
			this.E3.Name = "E3";
			this.E3.IsEditable = true;
			this.E3.InvisibleChar = '●';
			this.table3.Add(this.E3);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.E3]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E4 = new global::Gtk.Entry();
			this.E4.CanFocus = true;
			this.E4.Name = "E4";
			this.E4.IsEditable = true;
			this.E4.InvisibleChar = '●';
			this.table3.Add(this.E4);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.E4]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E5 = new global::Gtk.Entry();
			this.E5.CanFocus = true;
			this.E5.Name = "E5";
			this.E5.IsEditable = true;
			this.E5.InvisibleChar = '●';
			this.table3.Add(this.E5);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.E5]));
			w7.TopAttach = ((uint)(4));
			w7.BottomAttach = ((uint)(5));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E6 = new global::Gtk.Entry();
			this.E6.CanFocus = true;
			this.E6.Name = "E6";
			this.E6.IsEditable = true;
			this.E6.InvisibleChar = '●';
			this.table3.Add(this.E6);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.E6]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E7 = new global::Gtk.Entry();
			this.E7.CanFocus = true;
			this.E7.Name = "E7";
			this.E7.IsEditable = true;
			this.E7.InvisibleChar = '●';
			this.table3.Add(this.E7);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.E7]));
			w9.TopAttach = ((uint)(6));
			w9.BottomAttach = ((uint)(7));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E8 = new global::Gtk.Entry();
			this.E8.CanFocus = true;
			this.E8.Name = "E8";
			this.E8.IsEditable = true;
			this.E8.InvisibleChar = '●';
			this.table3.Add(this.E8);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table3[this.E8]));
			w10.TopAttach = ((uint)(7));
			w10.BottomAttach = ((uint)(8));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.E9 = new global::Gtk.Entry();
			this.E9.CanFocus = true;
			this.E9.Name = "E9";
			this.E9.IsEditable = true;
			this.E9.InvisibleChar = '●';
			this.table3.Add(this.E9);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table3[this.E9]));
			w11.TopAttach = ((uint)(8));
			w11.BottomAttach = ((uint)(9));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry24 = new global::Gtk.Entry();
			this.entry24.CanFocus = true;
			this.entry24.Name = "entry24";
			this.entry24.IsEditable = true;
			this.entry24.InvisibleChar = '●';
			this.table3.Add(this.entry24);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.entry24]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry26 = new global::Gtk.Entry();
			this.entry26.CanFocus = true;
			this.entry26.Name = "entry26";
			this.entry26.IsEditable = true;
			this.entry26.InvisibleChar = '●';
			this.table3.Add(this.entry26);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.entry26]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry28 = new global::Gtk.Entry();
			this.entry28.CanFocus = true;
			this.entry28.Name = "entry28";
			this.entry28.IsEditable = true;
			this.entry28.InvisibleChar = '●';
			this.table3.Add(this.entry28);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.entry28]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry30 = new global::Gtk.Entry();
			this.entry30.CanFocus = true;
			this.entry30.Name = "entry30";
			this.entry30.IsEditable = true;
			this.entry30.InvisibleChar = '●';
			this.table3.Add(this.entry30);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.entry30]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry32 = new global::Gtk.Entry();
			this.entry32.CanFocus = true;
			this.entry32.Name = "entry32";
			this.entry32.IsEditable = true;
			this.entry32.InvisibleChar = '●';
			this.table3.Add(this.entry32);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.entry32]));
			w16.TopAttach = ((uint)(4));
			w16.BottomAttach = ((uint)(5));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry34 = new global::Gtk.Entry();
			this.entry34.CanFocus = true;
			this.entry34.Name = "entry34";
			this.entry34.IsEditable = true;
			this.entry34.InvisibleChar = '●';
			this.table3.Add(this.entry34);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3[this.entry34]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry36 = new global::Gtk.Entry();
			this.entry36.CanFocus = true;
			this.entry36.Name = "entry36";
			this.entry36.IsEditable = true;
			this.entry36.InvisibleChar = '●';
			this.table3.Add(this.entry36);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3[this.entry36]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry38 = new global::Gtk.Entry();
			this.entry38.CanFocus = true;
			this.entry38.Name = "entry38";
			this.entry38.IsEditable = true;
			this.entry38.InvisibleChar = '●';
			this.table3.Add(this.entry38);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3[this.entry38]));
			w19.TopAttach = ((uint)(7));
			w19.BottomAttach = ((uint)(8));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry40 = new global::Gtk.Entry();
			this.entry40.CanFocus = true;
			this.entry40.Name = "entry40";
			this.entry40.IsEditable = true;
			this.entry40.InvisibleChar = '●';
			this.table3.Add(this.entry40);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3[this.entry40]));
			w20.TopAttach = ((uint)(8));
			w20.BottomAttach = ((uint)(9));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry42 = new global::Gtk.Entry();
			this.entry42.CanFocus = true;
			this.entry42.Name = "entry42";
			this.entry42.IsEditable = true;
			this.entry42.InvisibleChar = '●';
			this.table3.Add(this.entry42);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table3[this.entry42]));
			w21.TopAttach = ((uint)(9));
			w21.BottomAttach = ((uint)(10));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry44 = new global::Gtk.Entry();
			this.entry44.CanFocus = true;
			this.entry44.Name = "entry44";
			this.entry44.IsEditable = true;
			this.entry44.InvisibleChar = '●';
			this.table3.Add(this.entry44);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table3[this.entry44]));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry46 = new global::Gtk.Entry();
			this.entry46.CanFocus = true;
			this.entry46.Name = "entry46";
			this.entry46.IsEditable = true;
			this.entry46.InvisibleChar = '●';
			this.table3.Add(this.entry46);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table3[this.entry46]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry48 = new global::Gtk.Entry();
			this.entry48.CanFocus = true;
			this.entry48.Name = "entry48";
			this.entry48.IsEditable = true;
			this.entry48.InvisibleChar = '●';
			this.table3.Add(this.entry48);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3[this.entry48]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(2));
			w24.RightAttach = ((uint)(3));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry50 = new global::Gtk.Entry();
			this.entry50.CanFocus = true;
			this.entry50.Name = "entry50";
			this.entry50.IsEditable = true;
			this.entry50.InvisibleChar = '●';
			this.table3.Add(this.entry50);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3[this.entry50]));
			w25.TopAttach = ((uint)(3));
			w25.BottomAttach = ((uint)(4));
			w25.LeftAttach = ((uint)(2));
			w25.RightAttach = ((uint)(3));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry52 = new global::Gtk.Entry();
			this.entry52.CanFocus = true;
			this.entry52.Name = "entry52";
			this.entry52.IsEditable = true;
			this.entry52.InvisibleChar = '●';
			this.table3.Add(this.entry52);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3[this.entry52]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.LeftAttach = ((uint)(2));
			w26.RightAttach = ((uint)(3));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry54 = new global::Gtk.Entry();
			this.entry54.CanFocus = true;
			this.entry54.Name = "entry54";
			this.entry54.IsEditable = true;
			this.entry54.InvisibleChar = '●';
			this.table3.Add(this.entry54);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3[this.entry54]));
			w27.TopAttach = ((uint)(5));
			w27.BottomAttach = ((uint)(6));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry56 = new global::Gtk.Entry();
			this.entry56.CanFocus = true;
			this.entry56.Name = "entry56";
			this.entry56.IsEditable = true;
			this.entry56.InvisibleChar = '●';
			this.table3.Add(this.entry56);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3[this.entry56]));
			w28.TopAttach = ((uint)(6));
			w28.BottomAttach = ((uint)(7));
			w28.LeftAttach = ((uint)(2));
			w28.RightAttach = ((uint)(3));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry58 = new global::Gtk.Entry();
			this.entry58.CanFocus = true;
			this.entry58.Name = "entry58";
			this.entry58.IsEditable = true;
			this.entry58.InvisibleChar = '●';
			this.table3.Add(this.entry58);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3[this.entry58]));
			w29.TopAttach = ((uint)(7));
			w29.BottomAttach = ((uint)(8));
			w29.LeftAttach = ((uint)(2));
			w29.RightAttach = ((uint)(3));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry60 = new global::Gtk.Entry();
			this.entry60.CanFocus = true;
			this.entry60.Name = "entry60";
			this.entry60.IsEditable = true;
			this.entry60.InvisibleChar = '●';
			this.table3.Add(this.entry60);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table3[this.entry60]));
			w30.TopAttach = ((uint)(8));
			w30.BottomAttach = ((uint)(9));
			w30.LeftAttach = ((uint)(2));
			w30.RightAttach = ((uint)(3));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry62 = new global::Gtk.Entry();
			this.entry62.CanFocus = true;
			this.entry62.Name = "entry62";
			this.entry62.IsEditable = true;
			this.entry62.InvisibleChar = '●';
			this.table3.Add(this.entry62);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table3[this.entry62]));
			w31.TopAttach = ((uint)(9));
			w31.BottomAttach = ((uint)(10));
			w31.LeftAttach = ((uint)(2));
			w31.RightAttach = ((uint)(3));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed1.Add(this.table3);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table3]));
			w32.X = 148;
			w32.Y = 120;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.L_Ins = new global::Gtk.Label();
			this.L_Ins.Name = "L_Ins";
			this.L_Ins.LabelProp = global::Mono.Unix.Catalog.GetString("Ingresar datos:");
			this.fixed1.Add(this.L_Ins);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.L_Ins]));
			w33.X = 147;
			w33.Y = 80;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btn_Cnl = new global::Gtk.Button();
			this.btn_Cnl.WidthRequest = 100;
			this.btn_Cnl.CanFocus = true;
			this.btn_Cnl.Name = "btn_Cnl";
			this.btn_Cnl.UseUnderline = true;
			this.btn_Cnl.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btn_Cnl);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_Cnl]));
			w34.X = 546;
			w34.Y = 462;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btn_ok = new global::Gtk.Button();
			this.btn_ok.WidthRequest = 100;
			this.btn_ok.CanFocus = true;
			this.btn_ok.Name = "btn_ok";
			this.btn_ok.UseUnderline = true;
			this.btn_ok.Label = global::Mono.Unix.Catalog.GetString("Aceptar");
			this.fixed1.Add(this.btn_ok);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btn_ok]));
			w35.X = 422;
			w35.Y = 462;
			w1.Add(this.fixed1);
			this.scrolledwindow2.Add(w1);
			this.Add(this.scrolledwindow2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 799;
			this.DefaultHeight = 563;
			this.Show();
		}
	}
}
